"""Shared cross-cutting utilities and constants."""

from .env_utils import (
    env,
    get_schematic_layout_config,
    is_truthy_env,
    normalize_bool,
    normalize_number,
    normalize_text,
    parse_json_env,
    repo_root,
    to_float,
    to_int_env,
)
from .schema_contracts import CANONICAL_FIELD_CONTRACT_SCHEMAS, SCHEMA_FIELD_CONTRACTS, SUMMARY_STABLE_FIELDS
from .schema_versions import (
    CIRCUIT_MODEL_SCHEMA_VERSION,
    DSL_API_ENTITIES_SCHEMA_VERSION,
    DSL_API_REQUEST_SCHEMA_VERSION,
    DSL_API_RESULT_SCHEMA_VERSION,
    IR_SCHEMA_VERSION,
    KICAD_ERC_RESULT_SCHEMA_VERSION,
    KICAD_EXECUTION_PLAN_SCHEMA_VERSION,
    KICAD_PROJECT_WRITE_RESULT_SCHEMA_VERSION,
    NETLIST_SCHEMA_VERSION,
    NGSPICE_EXECUTION_SCHEMA_VERSION,
    NGSPICE_FEEDBACK_SCHEMA_VERSION,
    PART_LOCK_SCHEMA_VERSION,
    PROJECT_RESOLUTION_SCHEMA_VERSION,
    REQUIREMENT_SPEC_SCHEMA_VERSION,
    SIMULATION_PLAN_SCHEMA_VERSION,
    SIMULATION_PROFILE_SCHEMA_VERSION,
    SIMULATION_TASK_PLAN_SCHEMA_VERSION,
    SPICE_NETLIST_SCHEMA_VERSION,
    TEXT_TO_KICAD_SUMMARY_SCHEMA_VERSION,
    CANONICAL_SCHEMA_VERSIONS,
)
