"""Canonical schema version constants for pipeline outputs."""

from __future__ import annotations


REQUIREMENT_SPEC_SCHEMA_VERSION = "requirement-spec.v1"
CIRCUIT_MODEL_SCHEMA_VERSION = "circuit-model.v1"
NETLIST_SCHEMA_VERSION = "netlist.v1"
SPICE_NETLIST_SCHEMA_VERSION = "spice-netlist.v1"
NGSPICE_EXECUTION_SCHEMA_VERSION = "ngspice-execution.v1"
NGSPICE_FEEDBACK_SCHEMA_VERSION = "ngspice-feedback.v1"
KICAD_EXECUTION_PLAN_SCHEMA_VERSION = "kicad-execution-plan.v1"
KICAD_PROJECT_WRITE_RESULT_SCHEMA_VERSION = "kicad-project-write-result.v1"
KICAD_ERC_RESULT_SCHEMA_VERSION = "kicad-erc-result.v1"
TEXT_TO_KICAD_SUMMARY_SCHEMA_VERSION = "text-to-kicad-summary.v1"
PART_LOCK_SCHEMA_VERSION = "part-lock.v1"
SIMULATION_PROFILE_SCHEMA_VERSION = "simulation-profile.v1"
SIMULATION_PLAN_SCHEMA_VERSION = "simulation-plan.v1"

CANONICAL_SCHEMA_VERSIONS = (
    REQUIREMENT_SPEC_SCHEMA_VERSION,
    CIRCUIT_MODEL_SCHEMA_VERSION,
    NETLIST_SCHEMA_VERSION,
    SPICE_NETLIST_SCHEMA_VERSION,
    NGSPICE_EXECUTION_SCHEMA_VERSION,
    NGSPICE_FEEDBACK_SCHEMA_VERSION,
    KICAD_EXECUTION_PLAN_SCHEMA_VERSION,
    KICAD_PROJECT_WRITE_RESULT_SCHEMA_VERSION,
    KICAD_ERC_RESULT_SCHEMA_VERSION,
    TEXT_TO_KICAD_SUMMARY_SCHEMA_VERSION,
    PART_LOCK_SCHEMA_VERSION,
    SIMULATION_PROFILE_SCHEMA_VERSION,
    SIMULATION_PLAN_SCHEMA_VERSION,
)
