import type { BridgeCommandName, BridgeDomain } from './protocol';

export interface BridgeCommandDescriptor {
  name: BridgeCommandName;
  domain: BridgeDomain;
  requiresConfirmationByDefault: boolean;
  summary: string;
}

export const IMPLEMENTED_COMMANDS: BridgeCommandName[] = [
  'system.ping',
  'system.get_bridge_status',
  'system.get_environment',
  'system.api_invoke',
  'system.log_add',
  'system.log_clear',
  'system.log_export',
  'system.log_sort',
  'system.log_find',
  'system.panel_open_left',
  'system.panel_close_left',
  'system.panel_toggle_left_lock',
  'system.panel_is_left_locked',
  'system.panel_open_right',
  'system.panel_close_right',
  'system.panel_toggle_right_lock',
  'system.panel_is_right_locked',
  'system.panel_open_bottom',
  'system.panel_close_bottom',
  'system.panel_toggle_bottom_lock',
  'system.panel_is_bottom_locked',
  'system.window_open',
  'system.window_open_ui',
  'system.window_get_current_theme',
  'system.window_get_url_param',
  'system.window_get_url_anchor',
  'system.show_toast_message',
  'system.show_follow_mouse_tip',
  'system.remove_follow_mouse_tip',
  'system.show_information_message',
  'system.show_confirmation_message',
  'system.shortcut_get_shortcuts',
  'system.shortcut_register',
  'system.shortcut_unregister',
  'system.shortcut_list_registered',
  'system.timer_set_interval',
  'system.timer_clear_interval',
  'system.timer_set_timeout',
  'system.timer_clear_timeout',
  'system.right_click_change_menu',
  'system.callback_events_list',
  'system.callback_events_drain',
  'system.file_system_get_extension_file',
  'system.file_system_save_file',
  'system.file_system_save_file_to_file_system',
  'system.file_system_list_files',
  'system.file_system_delete_file',
  'system.file_system_get_eda_path',
  'system.file_system_get_documents_path',
  'system.file_system_get_libraries_paths',
  'system.file_system_get_projects_paths',
  'system.file_manager_get_project_file',
  'system.file_manager_get_document_file',
  'system.file_manager_get_document_source',
  'system.file_manager_get_document_footprint_sources',
  'system.file_manager_set_document_source',
  'system.file_manager_get_project_file_by_project_uuid',
  'system.file_manager_get_device_file_by_device_uuid',
  'system.file_manager_get_symbol_file_by_symbol_uuid',
  'system.storage_get_all_user_configs',
  'system.storage_set_all_user_configs',
  'system.storage_clear_all_user_configs',
  'system.storage_get_user_config',
  'system.storage_set_user_config',
  'system.storage_delete_user_config',
  'system.tool_netlist_comparison',
  'system.tool_schematic_comparison',
  'system.tool_pcb_comparison',
  'system.header_menu_replace',
  'system.header_menu_insert',
  'system.header_menu_remove',
  'system.header_menu_insert_system_item',
  'system.header_menu_remove_system_item',
  'system.format_conversion_ad_single',
  'system.format_conversion_ad_multi',
  'system.format_conversion_disa_single',
  'system.format_conversion_disa_multi',
  'project.get_inventory',
  'project.get_document_summary',
  'project.get_selection_snapshot',
  'project.list_workspaces',
  'project.list_teams',
  'project.list_involved_teams',
  'project.list_projects',
  'project.get_project_info',
  'project.open_project',
  'project.create_project',
  'project.list_schematics',
  'project.list_schematic_pages',
  'project.list_boards',
  'project.list_pcbs',
  'project.get_board_summary',
  'project.create_board',
  'project.open_document',
  'project.open_library_document',
  'project.close_document',
  'project.get_split_screen_tree',
  'project.get_split_screen_id_by_tab_id',
  'project.get_tabs_by_split_screen_id',
  'project.create_split_screen',
  'project.move_document_to_split_screen',
  'project.activate_document',
  'project.activate_split_screen',
  'project.tile_all_documents_to_split_screen',
  'project.merge_all_documents_from_split_screen',
  'project.get_current_rendered_area_image',
  'project.zoom_to_region',
  'project.zoom_to',
  'project.zoom_to_all_primitives',
  'project.zoom_to_selected_primitives',
  'project.export_bom',
  'schematic.get_current_schematic_info',
  'schematic.create_schematic',
  'schematic.create_schematic_page',
  'schematic.place_component',
  'schematic.create_wire',
  'schematic.annotate_net',
  'schematic.create_net_flag',
  'schematic.create_net_port',
  'schematic.create_short_circuit_flag',
  'schematic.import_changes',
  'schematic.save',
  'schematic.navigate_to_coordinates',
  'schematic.navigate_to_region',
  'schematic.get_primitive_at_point',
  'schematic.get_primitives_in_region',
  'schematic.get_current_filter_configuration',
  'schematic.auto_routing',
  'schematic.auto_layout',
  'schematic.check_drc',
  'pcb.get_board_summary',
  'pcb.get_current_pcb_info',
  'pcb.list_pcbs',
  'pcb.create_pcb',
  'pcb.place_footprint',
  'pcb.import_changes',
  'pcb.save',
  'pcb.get_calculating_ratline_status',
  'pcb.start_calculating_ratline',
  'pcb.stop_calculating_ratline',
  'pcb.convert_canvas_origin_to_data_origin',
  'pcb.convert_data_origin_to_canvas_origin',
  'pcb.get_canvas_origin',
  'pcb.set_canvas_origin',
  'pcb.navigate_to_coordinates',
  'pcb.navigate_to_region',
  'pcb.get_primitive_at_point',
  'pcb.get_primitives_in_region',
  'pcb.zoom_to_board_outline',
  'pcb.get_current_filter_configuration',
  'pcb.clear_routing',
  'project.save_panel',
];

export const SUPPORTED_COMMANDS: BridgeCommandDescriptor[] = [
  {
    name: 'system.ping',
    domain: 'system',
    requiresConfirmationByDefault: false,
    summary: 'Check whether the bridge runtime is reachable.',
  },
  {
    name: 'system.get_bridge_status',
    domain: 'system',
    requiresConfirmationByDefault: false,
    summary: 'Return bridge version and supported command metadata.',
  },
  {
    name: 'system.get_environment',
    domain: 'system',
    requiresConfirmationByDefault: false,
    summary: 'Return runtime, version, and user environment details.',
  },
  {
    name: 'system.api_invoke',
    domain: 'system',
    requiresConfirmationByDefault: true,
    summary: 'Invoke an arbitrary JLCEDA API path with explicit arguments.',
  },
  {
    name: 'system.log_add',
    domain: 'system',
    requiresConfirmationByDefault: false,
    summary: 'Add a line to the system log.',
  },
  {
    name: 'system.log_clear',
    domain: 'system',
    requiresConfirmationByDefault: false,
    summary: 'Clear the system log.',
  },
  {
    name: 'system.log_export',
    domain: 'system',
    requiresConfirmationByDefault: false,
    summary: 'Export the system log.',
  },
  {
    name: 'system.log_sort',
    domain: 'system',
    requiresConfirmationByDefault: false,
    summary: 'Filter and sort system log lines.',
  },
  {
    name: 'system.log_find',
    domain: 'system',
    requiresConfirmationByDefault: false,
    summary: 'Search system log lines by content.',
  },
  {
    name: 'system.panel_open_left',
    domain: 'system',
    requiresConfirmationByDefault: false,
    summary: 'Open the left panel.',
  },
  {
    name: 'system.panel_close_left',
    domain: 'system',
    requiresConfirmationByDefault: false,
    summary: 'Close the left panel.',
  },
  {
    name: 'system.panel_toggle_left_lock',
    domain: 'system',
    requiresConfirmationByDefault: false,
    summary: 'Toggle the left panel lock state.',
  },
  {
    name: 'system.panel_is_left_locked',
    domain: 'system',
    requiresConfirmationByDefault: false,
    summary: 'Inspect the left panel lock state.',
  },
  {
    name: 'system.panel_open_right',
    domain: 'system',
    requiresConfirmationByDefault: false,
    summary: 'Open the right panel.',
  },
  {
    name: 'system.panel_close_right',
    domain: 'system',
    requiresConfirmationByDefault: false,
    summary: 'Close the right panel.',
  },
  {
    name: 'system.panel_toggle_right_lock',
    domain: 'system',
    requiresConfirmationByDefault: false,
    summary: 'Toggle the right panel lock state.',
  },
  {
    name: 'system.panel_is_right_locked',
    domain: 'system',
    requiresConfirmationByDefault: false,
    summary: 'Inspect the right panel lock state.',
  },
  {
    name: 'system.panel_open_bottom',
    domain: 'system',
    requiresConfirmationByDefault: false,
    summary: 'Open the bottom panel.',
  },
  {
    name: 'system.panel_close_bottom',
    domain: 'system',
    requiresConfirmationByDefault: false,
    summary: 'Close the bottom panel.',
  },
  {
    name: 'system.panel_toggle_bottom_lock',
    domain: 'system',
    requiresConfirmationByDefault: false,
    summary: 'Toggle the bottom panel lock state.',
  },
  {
    name: 'system.panel_is_bottom_locked',
    domain: 'system',
    requiresConfirmationByDefault: false,
    summary: 'Inspect the bottom panel lock state.',
  },
  {
    name: 'system.window_open',
    domain: 'system',
    requiresConfirmationByDefault: false,
    summary: 'Open a browser or app window.',
  },
  {
    name: 'system.window_open_ui',
    domain: 'system',
    requiresConfirmationByDefault: false,
    summary: 'Open a named UI window.',
  },
  {
    name: 'system.window_get_current_theme',
    domain: 'system',
    requiresConfirmationByDefault: false,
    summary: 'Return the active UI theme.',
  },
  {
    name: 'system.window_get_url_param',
    domain: 'system',
    requiresConfirmationByDefault: false,
    summary: 'Return a URL query parameter.',
  },
  {
    name: 'system.window_get_url_anchor',
    domain: 'system',
    requiresConfirmationByDefault: false,
    summary: 'Return the URL hash anchor.',
  },
  {
    name: 'system.show_toast_message',
    domain: 'system',
    requiresConfirmationByDefault: false,
    summary: 'Show a toast message.',
  },
  {
    name: 'system.show_follow_mouse_tip',
    domain: 'system',
    requiresConfirmationByDefault: false,
    summary: 'Show a follow-mouse tip.',
  },
  {
    name: 'system.remove_follow_mouse_tip',
    domain: 'system',
    requiresConfirmationByDefault: false,
    summary: 'Remove a follow-mouse tip.',
  },
  {
    name: 'system.show_information_message',
    domain: 'system',
    requiresConfirmationByDefault: false,
    summary: 'Show an information message box.',
  },
  {
    name: 'system.show_confirmation_message',
    domain: 'system',
    requiresConfirmationByDefault: false,
    summary: 'Show a confirmation message box.',
  },
  {
    name: 'system.shortcut_get_shortcuts',
    domain: 'system',
    requiresConfirmationByDefault: false,
    summary: 'List registered shortcuts.',
  },
  {
    name: 'system.shortcut_register',
    domain: 'system',
    requiresConfirmationByDefault: true,
    summary: 'Register a shortcut key callback.',
  },
  {
    name: 'system.shortcut_unregister',
    domain: 'system',
    requiresConfirmationByDefault: true,
    summary: 'Unregister a shortcut key callback.',
  },
  {
    name: 'system.shortcut_list_registered',
    domain: 'system',
    requiresConfirmationByDefault: false,
    summary: 'List registered shortcut key callbacks.',
  },
  {
    name: 'system.timer_set_interval',
    domain: 'system',
    requiresConfirmationByDefault: true,
    summary: 'Register an interval timer callback.',
  },
  {
    name: 'system.timer_clear_interval',
    domain: 'system',
    requiresConfirmationByDefault: true,
    summary: 'Clear an interval timer callback.',
  },
  {
    name: 'system.timer_set_timeout',
    domain: 'system',
    requiresConfirmationByDefault: true,
    summary: 'Register a timeout timer callback.',
  },
  {
    name: 'system.timer_clear_timeout',
    domain: 'system',
    requiresConfirmationByDefault: true,
    summary: 'Clear a timeout timer callback.',
  },
  {
    name: 'system.right_click_change_menu',
    domain: 'system',
    requiresConfirmationByDefault: true,
    summary: 'Update the right-click menu callback.',
  },
  {
    name: 'system.callback_events_list',
    domain: 'system',
    requiresConfirmationByDefault: false,
    summary: 'Inspect recorded callback events.',
  },
  {
    name: 'system.callback_events_drain',
    domain: 'system',
    requiresConfirmationByDefault: false,
    summary: 'Drain recorded callback events.',
  },
  {
    name: 'system.file_system_get_extension_file',
    domain: 'system',
    requiresConfirmationByDefault: false,
    summary: 'Read an extension file from the packaged bundle.',
  },
  {
    name: 'system.file_system_save_file',
    domain: 'system',
    requiresConfirmationByDefault: false,
    summary: 'Save a file to the local filesystem.',
  },
  {
    name: 'system.file_system_save_file_to_file_system',
    domain: 'system',
    requiresConfirmationByDefault: true,
    summary: 'Save a file to a specific filesystem location.',
  },
  {
    name: 'system.file_system_list_files',
    domain: 'system',
    requiresConfirmationByDefault: false,
    summary: 'List files under a filesystem path.',
  },
  {
    name: 'system.file_system_delete_file',
    domain: 'system',
    requiresConfirmationByDefault: true,
    summary: 'Delete a file or folder in the filesystem.',
  },
  {
    name: 'system.file_system_get_eda_path',
    domain: 'system',
    requiresConfirmationByDefault: false,
    summary: 'Return the EDA installation path.',
  },
  {
    name: 'system.file_system_get_documents_path',
    domain: 'system',
    requiresConfirmationByDefault: false,
    summary: 'Return the document storage path.',
  },
  {
    name: 'system.file_system_get_libraries_paths',
    domain: 'system',
    requiresConfirmationByDefault: false,
    summary: 'Return the library storage paths.',
  },
  {
    name: 'system.file_system_get_projects_paths',
    domain: 'system',
    requiresConfirmationByDefault: false,
    summary: 'Return the project storage paths.',
  },
  {
    name: 'system.file_manager_get_project_file',
    domain: 'system',
    requiresConfirmationByDefault: false,
    summary: 'Export the current project file.',
  },
  {
    name: 'system.file_manager_get_document_file',
    domain: 'system',
    requiresConfirmationByDefault: false,
    summary: 'Export the current document file.',
  },
  {
    name: 'system.file_manager_get_document_source',
    domain: 'system',
    requiresConfirmationByDefault: false,
    summary: 'Return the current document source.',
  },
  {
    name: 'system.file_manager_get_document_footprint_sources',
    domain: 'system',
    requiresConfirmationByDefault: false,
    summary: 'Return footprint sources embedded in the current document.',
  },
  {
    name: 'system.file_manager_set_document_source',
    domain: 'system',
    requiresConfirmationByDefault: true,
    summary: 'Overwrite the current document source.',
  },
  {
    name: 'system.file_manager_get_project_file_by_project_uuid',
    domain: 'system',
    requiresConfirmationByDefault: false,
    summary: 'Export a project file by project UUID.',
  },
  {
    name: 'system.file_manager_get_device_file_by_device_uuid',
    domain: 'system',
    requiresConfirmationByDefault: false,
    summary: 'Export a device file by device UUID.',
  },
  {
    name: 'system.file_manager_get_symbol_file_by_symbol_uuid',
    domain: 'system',
    requiresConfirmationByDefault: false,
    summary: 'Export a symbol file by symbol UUID.',
  },
  {
    name: 'system.storage_get_all_user_configs',
    domain: 'system',
    requiresConfirmationByDefault: false,
    summary: 'Return all extension user configs.',
  },
  {
    name: 'system.storage_set_all_user_configs',
    domain: 'system',
    requiresConfirmationByDefault: false,
    summary: 'Replace all extension user configs.',
  },
  {
    name: 'system.storage_clear_all_user_configs',
    domain: 'system',
    requiresConfirmationByDefault: true,
    summary: 'Clear all extension user configs.',
  },
  {
    name: 'system.storage_get_user_config',
    domain: 'system',
    requiresConfirmationByDefault: false,
    summary: 'Read one extension user config.',
  },
  {
    name: 'system.storage_set_user_config',
    domain: 'system',
    requiresConfirmationByDefault: false,
    summary: 'Write one extension user config.',
  },
  {
    name: 'system.storage_delete_user_config',
    domain: 'system',
    requiresConfirmationByDefault: false,
    summary: 'Delete one extension user config.',
  },
  {
    name: 'system.tool_netlist_comparison',
    domain: 'system',
    requiresConfirmationByDefault: false,
    summary: 'Compare two netlists.',
  },
  {
    name: 'system.tool_schematic_comparison',
    domain: 'system',
    requiresConfirmationByDefault: false,
    summary: 'Compare two schematics.',
  },
  {
    name: 'system.tool_pcb_comparison',
    domain: 'system',
    requiresConfirmationByDefault: false,
    summary: 'Compare two PCBs.',
  },
  {
    name: 'system.header_menu_replace',
    domain: 'system',
    requiresConfirmationByDefault: false,
    summary: 'Replace the top menu layout.',
  },
  {
    name: 'system.header_menu_insert',
    domain: 'system',
    requiresConfirmationByDefault: false,
    summary: 'Insert top menu items.',
  },
  {
    name: 'system.header_menu_remove',
    domain: 'system',
    requiresConfirmationByDefault: false,
    summary: 'Remove top menu items.',
  },
  {
    name: 'system.header_menu_insert_system_item',
    domain: 'system',
    requiresConfirmationByDefault: false,
    summary: 'Insert a system top menu item.',
  },
  {
    name: 'system.header_menu_remove_system_item',
    domain: 'system',
    requiresConfirmationByDefault: false,
    summary: 'Remove a system top menu item.',
  },
  {
    name: 'system.format_conversion_ad_single',
    domain: 'system',
    requiresConfirmationByDefault: false,
    summary: 'Convert Altium library to one EasyEDA file.',
  },
  {
    name: 'system.format_conversion_ad_multi',
    domain: 'system',
    requiresConfirmationByDefault: false,
    summary: 'Convert Altium library to many EasyEDA files.',
  },
  {
    name: 'system.format_conversion_disa_single',
    domain: 'system',
    requiresConfirmationByDefault: false,
    summary: 'Convert DISA library to one EasyEDA file.',
  },
  {
    name: 'system.format_conversion_disa_multi',
    domain: 'system',
    requiresConfirmationByDefault: false,
    summary: 'Convert DISA library to many EasyEDA files.',
  },
  {
    name: 'project.get_inventory',
    domain: 'project',
    requiresConfirmationByDefault: false,
    summary: 'Return a broad inventory of the current project tree and related objects.',
  },
  {
    name: 'project.get_document_summary',
    domain: 'project',
    requiresConfirmationByDefault: false,
    summary: 'Return a compact summary of the current JLCEDA document.',
  },
  {
    name: 'project.get_selection_snapshot',
    domain: 'project',
    requiresConfirmationByDefault: false,
    summary: 'Return a structured snapshot of the current selection.',
  },
  {
    name: 'project.list_workspaces',
    domain: 'project',
    requiresConfirmationByDefault: false,
    summary: 'List all workspaces visible to the current account.',
  },
  {
    name: 'project.list_teams',
    domain: 'project',
    requiresConfirmationByDefault: false,
    summary: 'List all direct teams visible to the current account.',
  },
  {
    name: 'project.list_involved_teams',
    domain: 'project',
    requiresConfirmationByDefault: false,
    summary: 'List all teams the current account participates in.',
  },
  {
    name: 'project.list_projects',
    domain: 'project',
    requiresConfirmationByDefault: false,
    summary: 'List projects for a scope defined by team, folder, or workspace.',
  },
  {
    name: 'project.get_project_info',
    domain: 'project',
    requiresConfirmationByDefault: false,
    summary: 'Return brief metadata for a specific project.',
  },
  {
    name: 'project.open_project',
    domain: 'project',
    requiresConfirmationByDefault: true,
    summary: 'Open a project in the JLCEDA editor.',
  },
  {
    name: 'project.create_project',
    domain: 'project',
    requiresConfirmationByDefault: true,
    summary: 'Create a new project in the current account scope.',
  },
  {
    name: 'project.list_schematics',
    domain: 'project',
    requiresConfirmationByDefault: false,
    summary: 'List all schematics in the current project scope.',
  },
  {
    name: 'project.list_schematic_pages',
    domain: 'project',
    requiresConfirmationByDefault: false,
    summary: 'List schematic pages, optionally scoped to one schematic.',
  },
  {
    name: 'project.list_boards',
    domain: 'project',
    requiresConfirmationByDefault: false,
    summary: 'List all boards in the current project.',
  },
  {
    name: 'project.list_pcbs',
    domain: 'project',
    requiresConfirmationByDefault: false,
    summary: 'List all PCBs in the current project.',
  },
  {
    name: 'project.get_board_summary',
    domain: 'project',
    requiresConfirmationByDefault: false,
    summary: 'Return a board-centric summary of the current project.',
  },
  {
    name: 'project.create_board',
    domain: 'project',
    requiresConfirmationByDefault: true,
    summary: 'Create a board that links schematic and PCB documents.',
  },
  {
    name: 'project.open_document',
    domain: 'project',
    requiresConfirmationByDefault: false,
    summary: 'Open a document tab in the editor.',
  },
  {
    name: 'project.open_library_document',
    domain: 'project',
    requiresConfirmationByDefault: false,
    summary: 'Open a library symbol or footprint document.',
  },
  {
    name: 'project.close_document',
    domain: 'project',
    requiresConfirmationByDefault: true,
    summary: 'Close an editor tab.',
  },
  {
    name: 'project.get_split_screen_tree',
    domain: 'project',
    requiresConfirmationByDefault: false,
    summary: 'Return the current editor split-screen tree.',
  },
  {
    name: 'project.get_split_screen_id_by_tab_id',
    domain: 'project',
    requiresConfirmationByDefault: false,
    summary: 'Resolve a split-screen id from a tab id.',
  },
  {
    name: 'project.get_tabs_by_split_screen_id',
    domain: 'project',
    requiresConfirmationByDefault: false,
    summary: 'List tabs in a split-screen branch.',
  },
  {
    name: 'project.create_split_screen',
    domain: 'project',
    requiresConfirmationByDefault: false,
    summary: 'Split the editor into horizontal or vertical panes.',
  },
  {
    name: 'project.move_document_to_split_screen',
    domain: 'project',
    requiresConfirmationByDefault: false,
    summary: 'Move a tab to another split-screen pane.',
  },
  {
    name: 'project.activate_document',
    domain: 'project',
    requiresConfirmationByDefault: false,
    summary: 'Activate a specific editor tab.',
  },
  {
    name: 'project.activate_split_screen',
    domain: 'project',
    requiresConfirmationByDefault: false,
    summary: 'Activate a specific split-screen pane.',
  },
  {
    name: 'project.tile_all_documents_to_split_screen',
    domain: 'project',
    requiresConfirmationByDefault: false,
    summary: 'Tile all open documents into split screens.',
  },
  {
    name: 'project.merge_all_documents_from_split_screen',
    domain: 'project',
    requiresConfirmationByDefault: false,
    summary: 'Merge all split screens back to one pane.',
  },
  {
    name: 'project.get_current_rendered_area_image',
    domain: 'project',
    requiresConfirmationByDefault: false,
    summary: 'Return the current rendered area image metadata.',
  },
  {
    name: 'project.zoom_to_region',
    domain: 'project',
    requiresConfirmationByDefault: false,
    summary: 'Zoom the editor to a rectangular region.',
  },
  {
    name: 'project.zoom_to',
    domain: 'project',
    requiresConfirmationByDefault: false,
    summary: 'Zoom the editor to a coordinate and scale.',
  },
  {
    name: 'project.zoom_to_all_primitives',
    domain: 'project',
    requiresConfirmationByDefault: false,
    summary: 'Zoom the editor to all primitives in view.',
  },
  {
    name: 'project.zoom_to_selected_primitives',
    domain: 'project',
    requiresConfirmationByDefault: false,
    summary: 'Zoom the editor to the selected primitives.',
  },
  {
    name: 'project.export_bom',
    domain: 'project',
    requiresConfirmationByDefault: true,
    summary: 'Export a BOM artifact for the current project.',
  },
  {
    name: 'schematic.get_current_schematic_info',
    domain: 'schematic',
    requiresConfirmationByDefault: false,
    summary: 'Return detailed metadata for the current schematic.',
  },
  {
    name: 'schematic.create_schematic',
    domain: 'schematic',
    requiresConfirmationByDefault: true,
    summary: 'Create a schematic in the current project.',
  },
  {
    name: 'schematic.create_schematic_page',
    domain: 'schematic',
    requiresConfirmationByDefault: true,
    summary: 'Create a schematic page in a specific schematic.',
  },
  {
    name: 'schematic.place_component',
    domain: 'schematic',
    requiresConfirmationByDefault: true,
    summary: 'Place a component at a specific schematic position.',
  },
  {
    name: 'schematic.create_wire',
    domain: 'schematic',
    requiresConfirmationByDefault: true,
    summary: 'Create a schematic wire with explicit points.',
  },
  {
    name: 'schematic.annotate_net',
    domain: 'schematic',
    requiresConfirmationByDefault: true,
    summary: 'Add or update a schematic net label.',
  },
  {
    name: 'schematic.create_net_flag',
    domain: 'schematic',
    requiresConfirmationByDefault: true,
    summary: 'Create a schematic net flag symbol.',
  },
  {
    name: 'schematic.create_net_port',
    domain: 'schematic',
    requiresConfirmationByDefault: true,
    summary: 'Create a schematic net port symbol.',
  },
  {
    name: 'schematic.create_short_circuit_flag',
    domain: 'schematic',
    requiresConfirmationByDefault: true,
    summary: 'Create a schematic short-circuit flag.',
  },
  {
    name: 'schematic.import_changes',
    domain: 'schematic',
    requiresConfirmationByDefault: true,
    summary: 'Import PCB-driven changes into the schematic.',
  },
  {
    name: 'schematic.save',
    domain: 'schematic',
    requiresConfirmationByDefault: false,
    summary: 'Save the current schematic.',
  },
  {
    name: 'schematic.navigate_to_coordinates',
    domain: 'schematic',
    requiresConfirmationByDefault: false,
    summary: 'Navigate the schematic canvas to a point.',
  },
  {
    name: 'schematic.navigate_to_region',
    domain: 'schematic',
    requiresConfirmationByDefault: false,
    summary: 'Navigate the schematic canvas to a region.',
  },
  {
    name: 'schematic.get_primitive_at_point',
    domain: 'schematic',
    requiresConfirmationByDefault: false,
    summary: 'Inspect the schematic primitive at a point.',
  },
  {
    name: 'schematic.get_primitives_in_region',
    domain: 'schematic',
    requiresConfirmationByDefault: false,
    summary: 'Inspect schematic primitives in a region.',
  },
  {
    name: 'schematic.get_current_filter_configuration',
    domain: 'schematic',
    requiresConfirmationByDefault: false,
    summary: 'Return the current schematic filter configuration.',
  },
  {
    name: 'schematic.auto_routing',
    domain: 'schematic',
    requiresConfirmationByDefault: true,
    summary: 'Run schematic auto-routing.',
  },
  {
    name: 'schematic.auto_layout',
    domain: 'schematic',
    requiresConfirmationByDefault: true,
    summary: 'Run schematic auto-layout.',
  },
  {
    name: 'schematic.check_drc',
    domain: 'schematic',
    requiresConfirmationByDefault: true,
    summary: 'Run schematic DRC checks.',
  },
  {
    name: 'pcb.get_board_summary',
    domain: 'pcb',
    requiresConfirmationByDefault: false,
    summary: 'Return a compact summary of the current PCB board.',
  },
  {
    name: 'pcb.get_current_pcb_info',
    domain: 'pcb',
    requiresConfirmationByDefault: false,
    summary: 'Return detailed metadata for the current PCB.',
  },
  {
    name: 'pcb.list_pcbs',
    domain: 'pcb',
    requiresConfirmationByDefault: false,
    summary: 'List all PCBs in the current project.',
  },
  {
    name: 'pcb.create_pcb',
    domain: 'pcb',
    requiresConfirmationByDefault: true,
    summary: 'Create a PCB in the current project.',
  },
  {
    name: 'pcb.place_footprint',
    domain: 'pcb',
    requiresConfirmationByDefault: true,
    summary: 'Place a footprint on the PCB at a specific coordinate.',
  },
  {
    name: 'pcb.import_changes',
    domain: 'pcb',
    requiresConfirmationByDefault: true,
    summary: 'Import schematic changes into the PCB.',
  },
  {
    name: 'pcb.save',
    domain: 'pcb',
    requiresConfirmationByDefault: false,
    summary: 'Save the current PCB.',
  },
  {
    name: 'pcb.get_calculating_ratline_status',
    domain: 'pcb',
    requiresConfirmationByDefault: false,
    summary: 'Return PCB ratline calculation status.',
  },
  {
    name: 'pcb.start_calculating_ratline',
    domain: 'pcb',
    requiresConfirmationByDefault: true,
    summary: 'Start PCB ratline calculation.',
  },
  {
    name: 'pcb.stop_calculating_ratline',
    domain: 'pcb',
    requiresConfirmationByDefault: true,
    summary: 'Stop PCB ratline calculation.',
  },
  {
    name: 'pcb.convert_canvas_origin_to_data_origin',
    domain: 'pcb',
    requiresConfirmationByDefault: false,
    summary: 'Convert PCB canvas coordinates to data coordinates.',
  },
  {
    name: 'pcb.convert_data_origin_to_canvas_origin',
    domain: 'pcb',
    requiresConfirmationByDefault: false,
    summary: 'Convert PCB data coordinates to canvas coordinates.',
  },
  {
    name: 'pcb.get_canvas_origin',
    domain: 'pcb',
    requiresConfirmationByDefault: false,
    summary: 'Return the current PCB canvas origin.',
  },
  {
    name: 'pcb.set_canvas_origin',
    domain: 'pcb',
    requiresConfirmationByDefault: true,
    summary: 'Set the PCB canvas origin.',
  },
  {
    name: 'pcb.navigate_to_coordinates',
    domain: 'pcb',
    requiresConfirmationByDefault: false,
    summary: 'Navigate the PCB canvas to a point.',
  },
  {
    name: 'pcb.navigate_to_region',
    domain: 'pcb',
    requiresConfirmationByDefault: false,
    summary: 'Navigate the PCB canvas to a region.',
  },
  {
    name: 'pcb.get_primitive_at_point',
    domain: 'pcb',
    requiresConfirmationByDefault: false,
    summary: 'Inspect the PCB primitive at a point.',
  },
  {
    name: 'pcb.get_primitives_in_region',
    domain: 'pcb',
    requiresConfirmationByDefault: false,
    summary: 'Inspect PCB primitives in a region.',
  },
  {
    name: 'pcb.zoom_to_board_outline',
    domain: 'pcb',
    requiresConfirmationByDefault: false,
    summary: 'Zoom the PCB to the board outline.',
  },
  {
    name: 'pcb.get_current_filter_configuration',
    domain: 'pcb',
    requiresConfirmationByDefault: false,
    summary: 'Return the current PCB filter configuration.',
  },
  {
    name: 'pcb.clear_routing',
    domain: 'pcb',
    requiresConfirmationByDefault: true,
    summary: 'Clear PCB routing by scope.',
  },
  {
    name: 'project.save_panel',
    domain: 'project',
    requiresConfirmationByDefault: false,
    summary: 'Save the current panel document.',
  },
];

export function getSupportedCommandNames(): Array<BridgeCommandName> {
  return SUPPORTED_COMMANDS.map(command => command.name);
}

export function getCommandDescriptor(name: BridgeCommandName): BridgeCommandDescriptor | undefined {
  return SUPPORTED_COMMANDS.find(command => command.name === name);
}

export function isCommandImplemented(name: BridgeCommandName): boolean {
  return IMPLEMENTED_COMMANDS.includes(name);
}
